### ISSUE TITLE
Use integrated package managment

### ISSUE THREAD

**Issue by eclarke** [sunbeam-labs/sbx_report#10]
We should rewrite the rules to use their own conda environments, as the dependencies here may conflict with other extensions.

https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#integrated-package-management

**Comment by ressy** [comment]
Just made a pull request that I think should cover this one.   (It's a simpler situation than [the related sbx_kaiju issue](https://github.com/sunbeam-labs/sbx_kaiju/issues/4) since there's just one self-contained rule and no need to interact with the software inside the isolated environment.)
